version: '3.8'

services:
  backend-app:
    image: 746200881003.dkr.ecr.us-east-1.amazonaws.com/enis-app:backend-app-latest  # Use the already built image
    container_name: backend-app
    restart: always
    ports:
      - "8001:8000"
    networks:
      - my_bridge
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin/login/?next=/admin/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend-app:
    image: 746200881003.dkr.ecr.us-east-1.amazonaws.com/enis-app:frontend-app-latest  
    container_name: frontend-app
    restart: always
    ports:
      - "81:80"
    depends_on:
      backend-app:
        condition: service_healthy
    networks:
      - my_bridge
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
volumes:
  db_data:
 
networks:
  my_bridge:
    external: true
